# Nova Desktop - Main Makefile
# BSD Make build system for Nova Desktop components

.include <bsd.own.mk>

SUBDIR=		compositor \
		shell \
		services \
		login \
		lib

SUBDIR_PARALLEL=

.include <bsd.subdir.mk>
